### PR TITLE
Added config file storage and simple handler for it

### PR DESCRIPTION
**Pull request by arodiss**

### CODE REVIEW

**Comment by matsjoyce** [comment]
@arodiss I've created an alternate version that changes less at #5. What do you think?

**Comment by arodiss** [comment]
@matsjoyce 
Well, my version is configurable interactively - of course it's absolutely not necessary in simple project like this, so you can use either

**Comment by matsjoyce** [comment]
Interactively?

**Comment by arodiss** [comment]
@matsjoyce 
Well, this python `input()` thing is sort of interaction, you know

My handler interactively asks for values only when it needs'em. I.e. I don't do autoupload and thus am never asked for login / pass, but you would be asked (once)

**Comment by matsjoyce** [comment]
Mine works the same way. The only difference is that it won't automatically store them afterwards.

**Comment by arodiss** [comment]
@matsjoyce 
... and thus will ask you on every run. Not nice IMO

Well, this all is not worth a rotten egg - let's go with yours, I will add git pull there

**Comment by matsjoyce** [comment]
Well, yes, it will ask every time, but it's less of a security risk that way. Though I guess this is all kind of pointless since no one but us two currently uses this and we know how to configure it... And I suppose if you never use autoupload then the security part is not really a concern at all for you. :grin: Programming can be fun like that...

**Comment by arodiss** [comment]
@matsjoyce 
BTW, can you please port [this change](https://github.com/matsjoyce/LotIWikiGen/pull/3/files#diff-8e206872b2001fb8e069ea287522c685R111) to master?
For me it does not work otherwise

**Comment by matsjoyce** [comment]
Which change? The `str(start)` change is in 02dd8997ccdc654242e1d4fcc8149746b6dfcefe.

**Comment by arodiss** [comment]
@matsjoyce 
yes, this one - thank you

**Pull request closed without merging**
